using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using System.Text;

namespace ERCOT_API_dashboard.SourceGenerators.WindForecast
{
    [Generator]
    public class WindForecastSortFieldsGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Find all classes with properties
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax cds && cds.Members.OfType<PropertyDeclarationSyntax>().Any(),
                    transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
                .Where(c => c is not null);

            var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

            context.RegisterSourceOutput(compilationAndClasses, (spc, source) =>
            {
                var (compilation, classes) = source;

                var sortableAttr = compilation.GetTypeByMetadataName("ERCOT_API_dashboard.Server.Models.WindForecast.SortableAttribute");
                if (sortableAttr == null) return;

                foreach (var classDecl in classes.Distinct())
                {
                    var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
                    if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
                        continue;

                    var sortableProps = classSymbol
                        .GetMembers()
                        .OfType<IPropertySymbol>()
                        .Where(p => p.GetAttributes().Any(attr => SymbolEqualityComparer.Default.Equals(attr.AttributeClass, sortableAttr)))
                        .ToArray();

                    if (!sortableProps.Any()) continue;

                    var ns = classSymbol.ContainingNamespace.ToDisplayString();
                    var typeName = classSymbol.Name;
                    var generatedEnumName = $"{typeName}SortFields";

                    var sb = new StringBuilder();
                    sb.AppendLine("// <auto-generated />");
                    sb.AppendLine($"namespace {ns};");
                    sb.AppendLine($"public enum {generatedEnumName}");
                    sb.AppendLine("{");

                    foreach (var prop in sortableProps)
                        sb.AppendLine($"    {prop.Name},");
                                        
                    sb.AppendLine("}");

                    spc.AddSource($"{generatedEnumName}.g.cs", sb.ToString());
                }
            });
        }
    }
}
